baseURL = 'https://LeVarez.github.io/'
languageCode = 'es'
title = 'LeVarez'

theme="hugo-coder"
enableEmoji = true
DefaultContentLanguage = 'es'

[params]
author = "LeVarez"
description = "Página personal de LeVarez"
keywords = "blog,developer,personal"
info = []
avatarURL = "images/avatar.jpg"
dateFormat = "2 January de 2006"
since = 2021

# Right To Left, shift content direction for languagues such as Arabic
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/levarez/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"